/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    BaseButton: typeof import('./components/reusables/BaseButton.vue')['default']
    BaseInputField: typeof import('./components/reusables/BaseInputField.vue')['default']
    BaseSelect: typeof import('./components/reusables/BaseSelect.vue')['default']
    BaseTab: typeof import('./components/reusables/BaseTab.vue')['default']
    DialogLoader: typeof import('./components/DialogLoader.vue')['default']
    DialogLoading: typeof import('./components/DialogLoading.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    Table: typeof import('./components/Table.vue')['default']
  }
}
